// Catalog of AI agents Audcomp can build, score, and ship.
// Used by the AI Agent landing page, the agent-fit assessment, and the dashboard widget.

export interface AgentCatalogEntry {
    id: string;
    name: string;          // display name e.g. "Marketing Orchestrator"
    slug: string;          // kebab name e.g. "marketing-orchestrator"
    department: 'sales' | 'marketing' | 'customer_service' | 'operations' | 'finance_hr';
    description: string;   // short, customer-facing
    tools: string[];       // sample tools the agent uses
    color: 'violet' | 'cyan' | 'emerald' | 'amber' | 'rose' | 'sky' | 'pink' | 'lime';
    icon: string;          // lucide icon name
    sampleStats: { successRate: number; lastRunLabel: string };
}

export const AGENT_CATALOG: AgentCatalogEntry[] = [
    // ── Sales ─────────────────────────────────────────────
    { id: 'lead-hunter',           name: 'Lead Hunter',           slug: 'lead-hunter',           department: 'sales',           description: 'Finds high-fit accounts, scrapes contacts, and queues them for outreach using Apollo, LinkedIn, and Google Places.',                 tools: ['Apollo', 'LinkedIn', 'Google Places', 'Apify'],   color: 'cyan',    icon: 'Target',         sampleStats: { successRate: 89, lastRunLabel: '6h ago' } },
    { id: 'lead-enricher',         name: 'Lead Enricher',         slug: 'lead-enricher',         department: 'sales',           description: 'Cleans and enriches every record — emails, LinkedIn URLs, decision-maker info, firmographics — so reps work clean lists.',           tools: ['Clearbit', 'Hunter', 'Apollo', 'Apify'],          color: 'cyan',    icon: 'Database',       sampleStats: { successRate: 83, lastRunLabel: '6h ago' } },
    { id: 'outreach-strategist',   name: 'Outreach Strategist',   slug: 'outreach-strategist',   department: 'sales',           description: 'Drafts personalized cold emails and LinkedIn DMs, builds multi-touch sequences, and pauses on reply.',                                tools: ['Instantly', 'LinkedIn', 'Resend', 'Claude'],      color: 'amber',   icon: 'MessageSquare',  sampleStats: { successRate: 81, lastRunLabel: '2h ago' } },
    { id: 'crm-hygiene',           name: 'CRM Hygiene Agent',     slug: 'crm-hygiene',           department: 'sales',           description: 'Captures call notes, extracts next steps, and updates CRM records automatically from email + meeting transcripts.',                  tools: ['HubSpot', 'Salesforce', 'Otter', 'Claude'],       color: 'sky',     icon: 'ClipboardCheck', sampleStats: { successRate: 78, lastRunLabel: '4h ago' } },
    // ── Marketing ─────────────────────────────────────────
    { id: 'marketing-orchestrator',name: 'Marketing Orchestrator',slug: 'marketing-orchestrator',department: 'marketing',       description: 'Top-level brain that coordinates every marketing sub-agent — calendar, content, social, and email — against your goals.',                tools: ['Bash', 'Read', 'Write', 'Agent'],                 color: 'violet',  icon: 'Sparkles',       sampleStats: { successRate: 87, lastRunLabel: 'Just now' } },
    { id: 'content-strategist',    name: 'Content Strategist',    slug: 'content-strategist',    department: 'marketing',       description: 'Plans the seasonal content calendar around launches, holidays, and local events your customers care about.',                            tools: ['Notion', 'Calendar', 'Claude'],                   color: 'pink',    icon: 'BookOpen',       sampleStats: { successRate: 84, lastRunLabel: '1h ago' } },
    { id: 'caption-writer',        name: 'Caption Writer',        slug: 'caption-writer',        department: 'marketing',       description: 'Writes captions, blog copy, and ad copy in your brand voice — drafts queued for human review before publish.',                          tools: ['Claude', 'OpenAI', 'Brand Voice DB'],             color: 'pink',    icon: 'PenLine',        sampleStats: { successRate: 91, lastRunLabel: '30m ago' } },
    { id: 'visual-director',       name: 'Visual Director',       slug: 'visual-director',       department: 'marketing',       description: 'Storyboards reels, finds trending visuals, and locks the creative direction for every shoot.',                                          tools: ['Pinterest', 'Midjourney', 'Claude'],              color: 'pink',    icon: 'Camera',         sampleStats: { successRate: 76, lastRunLabel: '3h ago' } },
    { id: 'scheduler',             name: 'Scheduler',             slug: 'scheduler',             department: 'marketing',       description: 'Pushes approved posts to Instagram, Facebook, TikTok, YouTube, and Google Business at the right times.',                                tools: ['Meta Graph API', 'TikTok API', 'Google Business'],color: 'lime',    icon: 'CalendarDays',   sampleStats: { successRate: 95, lastRunLabel: '15m ago' } },
    { id: 'seo-geo-agent',         name: 'SEO & GEO Agent',       slug: 'seo-geo-agent',         department: 'marketing',       description: 'Keyword research, topic clusters, on-page audits, and AI-search optimization — keeps you cited by ChatGPT and Google AI Overviews.',  tools: ['Ahrefs', 'Search Console', 'Claude'],             color: 'violet',  icon: 'Search',         sampleStats: { successRate: 80, lastRunLabel: '5h ago' } },
    // ── Customer Service ──────────────────────────────────
    { id: 'engagement-responder',  name: 'Engagement Responder',  slug: 'engagement-responder',  department: 'customer_service',description: 'Handles Instagram, Facebook, and TikTok DMs and comments — quotes, availability, order questions, after hours coverage.',              tools: ['Meta Inbox', 'Claude', 'Knowledge Base'],         color: 'emerald', icon: 'MessageCircle',  sampleStats: { successRate: 88, lastRunLabel: 'Just now' } },
    { id: 'tier1-ticket-agent',    name: 'Tier-1 Ticket Agent',   slug: 'tier1-ticket-agent',    department: 'customer_service',description: 'Answers FAQs and handles common requests instantly using your help docs — escalates only when a human is genuinely needed.',         tools: ['Zendesk', 'Intercom', 'Claude'],                  color: 'emerald', icon: 'Bot',            sampleStats: { successRate: 86, lastRunLabel: '20m ago' } },
    { id: 'voc-agent',             name: 'Voice-of-Customer Agent',slug: 'voc-agent',            department: 'customer_service',description: 'Reads reviews, support tickets, and NPS comments — surfaces recurring themes weekly so product and ops can act fast.',                  tools: ['Trustpilot', 'GA4', 'Claude'],                    color: 'emerald', icon: 'BarChart3',      sampleStats: { successRate: 79, lastRunLabel: '12h ago' } },
    // ── Operations ────────────────────────────────────────
    { id: 'special-events-coord',  name: 'Special Events Coordinator',slug: 'special-events-coord',department: 'operations',     description: 'Tracks weddings, funerals, corporate events, and bookings — auto-preps reminders, checklists, and timelines.',                          tools: ['Calendar', 'SharePoint', 'Claude'],               color: 'amber',   icon: 'Calendar',       sampleStats: { successRate: 92, lastRunLabel: '2h ago' } },
    { id: 'doc-extraction-agent',  name: 'Document Extraction Agent',slug: 'doc-extraction-agent',department: 'operations',     description: 'Pulls structured data from invoices, POs, contracts, and forms — pushes results straight into accounting or your LOB system.',         tools: ['Azure Doc Intelligence', 'Claude', 'Vision'],     color: 'sky',     icon: 'FileText',       sampleStats: { successRate: 94, lastRunLabel: '1h ago' } },
    { id: 'sop-knowledge-agent',   name: 'SOP & Knowledge Agent', slug: 'sop-knowledge-agent',   department: 'operations',       description: 'Internal AI that answers "how do we…" questions instantly using your SOPs and past tickets — onboarding hours drop dramatically.',     tools: ['SharePoint', 'Notion', 'Claude'],                 color: 'violet',  icon: 'BookOpen',       sampleStats: { successRate: 82, lastRunLabel: '45m ago' } },
    // ── Finance / HR ──────────────────────────────────────
    { id: 'ap-invoice-agent',      name: 'AP Invoice Agent',      slug: 'ap-invoice-agent',      department: 'finance_hr',      description: 'Reads inbound invoices, matches to POs and receipts, flags exceptions, and queues clean invoices for one-click approval.',             tools: ['QuickBooks', 'Xero', 'Claude'],                   color: 'emerald', icon: 'BarChart3',      sampleStats: { successRate: 90, lastRunLabel: '3h ago' } },
    { id: 'recruiting-agent',      name: 'Recruiting & Screening Agent',slug: 'recruiting-agent',department: 'finance_hr',      description: 'Screens inbound resumes against your role criteria, ranks candidates, drafts outreach, and books first-round calls.',                  tools: ['LinkedIn', 'Greenhouse', 'Claude'],               color: 'rose',    icon: 'Users',          sampleStats: { successRate: 77, lastRunLabel: '7h ago' } },
];
